# @software: PyCharm
# @author: Lionel Johnson
# @contact: https://fairy.host
# @organization: https://github.com/FairylandFuture
# @datetime: 2024-04-19 18:08:46 UTC+08:00
---
mysql:
  host: localhost
  port: 3306
  user: root
  password: root
  database: mysql
postgresql:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: postgres
  schema: public
