# @software: PyCharm
# @author: Lionel Johnson
# @contact: https://fairy.host
# @organization: https://github.com/FairylandFuture
# @datetime: 2024-05-11 11:58:40 UTC+08:00
---
name: Build Version

on:
  workflow_dispatch:
  push:
    branches:
      - "Pre-release"
    paths:
      - "**"

jobs:
  build-version:
    runs-on: ubuntu-latest

    steps:
      - name: Step1 - Checkout
        uses: actions/checkout@v2

      - name: Step2 - Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Step3 - Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Step4 - Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/workflows/buildversion.py

      - name: Step5 - Push changes to Pre-release
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b Pre-release || git checkout Pre-release
          git pull
          git add conf/release/buildversion fairylandfuture/conf/release/buildversion
          git commit -m ":wrench: Update commit count" || echo "No changes to commit"
          git push origin Pre-release
